module.exports = {
  CLIENT_STATE: {
    UNINITIALIZED: 0,
    CONNECTED: 1,
    CONNECTING: 2
  },
  ERRORS: {
    CLIENT: {
      CONNECT_WHILST_CONNECTING: 0,
      CONNECT_ERROR: 1,
      DISCONNECTED_WRITE: 2,
      CONNECT_BAD_URI: 3,
      RESPONSE_TIMEOUT: 4
    },
    SERVER: {
      CONFIG_ERROR: 100
    }
  }
};
