module.exports = {
  CLIENT_STATE: {
    UNINITIALIZED: 0,
    CONNECTED: 1,
    CONNECTING: 2
  },
  CACHE_STATE:{
    UNINITIALIZED: 0,
    CONNECTED: 1,
    RECONNECTING:2,
    CLOSED:3
  },
  //TODO: we'll need more here: https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent
  WS_CLOSE_REASON:{
    NORMAL:1000,
    GOING_AWAY:1001,
    PROTOCOL_ERROR:1002,
    UNSUPPORTED_DATA:1003,
    ABNORMAL:1006
  },
  ERRORS: {
    CLIENT: {
      CONNECT_ERROR: 0,
      DISCONNECTED_WRITE: 1,
      RESPONSE_TIMEOUT: 2,
      CONFIG_ERROR: 3,
      ERROR: 4,
      TIMEOUT_ERROR: 5
    },
    SERVER: {
      CONFIG_ERROR: 100,
      JOIN_ERROR: 101,
      UNCONNECTED_SOCKET_ERROR: 102,
      NO_SUCH_PEER_ERROR: 103,
      REQUEST_TIMEOUT_ERROR: 104,
      REQUEST_TO_DEPARTED_ERROR: 105
    }
  }
};
