module.exports = {
  CLIENT_STATE: {
    UNINITIALIZED: 0,
    CONNECTED: 1,
    CONNECTING: 2
  },
  CACHE_STATE:{
    UNINITIALIZED: 0,
    CONNECTED: 1,
    RECONNECTING:2,
    CLOSED:3
  },
  ERRORS: {
    CLIENT: {
      CONNECT_ERROR: 0,
      DISCONNECTED_WRITE: 1,
      RESPONSE_TIMEOUT: 2,
      CONFIG_ERROR: 3,
      ERROR: 4,
      TIMEOUT_ERROR: 5
    },
    SERVER: {
      CONFIG_ERROR: 100,
      JOIN_ERROR: 101,
      UNCONNECTED_SOCKET_ERROR: 102
    }
  }
};
